<?php
    $version = date('YmdHis');
    // Daftar halaman dan lokasi file JS-nya
    $pages = [
        "ProfileUser"               => "_Page/ProfileUser/ProfileUser.js?v='.$version.'",
        "Bantuan"                   => "_Page/Bantuan/Bantuan.js",
        "Help"                      => "_Page/Bantuan/Bantuan.js",
        "Akses"                     => "_Page/Akses/Akses.js",
        "Aksesibilitas"             => "_Page/Aksesibilitas/Aksesibilitas.js",
        "SettingProfile"            => "_Page/ProfileFaskes/ProfileFaskes.js",
        "Referensi"                 => "_Page/Referensi/Referensi.js",
        "SettingBridging"           => "_Page/SettingBridging/SettingBridging.js",
        "Log"                       => "_Page/Log/Log.js",
        "Database"                  => "_Page/Database/Database.js",
        "Poliklinik"                => "_Page/Poliklinik/Poliklinik.js",
        "Dokter"                    => "_Page/Dokter/Dokter.js",
        "JadwalDokter"              => "_Page/JadwalDokter/JadwalDokter.js",
        "Wilayah"                   => "_Page/Wilayah/Wilayah.js",
        "KelasRuangan"              => "_Page/KelasRuangan/KelasRuangan.js",
        "KelasRuangan2"             => "_Page/KelasRuangan2/KelasRuangan2.js?v='.$version.'",
        "Pasien"                    => "_Page/Pasien/Pasien.js",
        "RawatJalan"                => "_Page/RawatJalan/RawatJalan.js",
        "SuratKontrol"              => "_Page/SuratKontrol/SuratKontrol.js",
        "Approval"                  => "_Page/Approval/Approval.js",
        "Rujukan"                   => "_Page/Rujukan/Rujukan.js",
        "Fingerprint"               => "_Page/Fingerprint/Fingerprint.js",
        "Monitoring"                => "_Page/Monitoring/Monitoring.js",
        "MonitoringBaru"            => "_Page/MonitoringBaru/MonitoringBaru.js",
        "Signature"                 => "_Page/Signature/Signature.js",
        "Antrian"                   => "_Page/Antrian/Antrian.js",
        "MonitorAntrian"            => "_Page/MonitorAntrian/MonitorAntrian.js",
        "AntrianPanggil"            => "_Page/AntrianPanggil/AntrianPanggil.js",
        "MonitorRuangan"            => "_Page/MonitorRuangan/MonitorRuangan.js",
        "JadwalOperasi"             => "_Page/JadwalOperasi/JadwalOperasi.js",
        "Diagnosa"                  => "_Page/Diagnosa/Diagnosa.js",
        "SettingPercetakan"         => "_Page/SettingPercetakan/SettingPercetakan.js",
        "Obat"                      => "_Page/Obat/Obat.js",
        "ObatStorage"               => "_Page/ObatStorage/ObatStorage.js",
        "WebSetting"                => "_Page/WebSetting/WebSetting.js",
        "WebTentang"                => "_Page/WebTentang/WebTentang.js",
        "WebMetaTag"                => "_Page/WebMetaTag/WebMetaTag.js",
        "WebSlider"                 => "_Page/WebSlider/WebSlider.js",
        "WebFAQ"                    => "_Page/WebFAQ/WebFAQ.js",
        "WebMedsos"                 => "_Page/WebMedsos/WebMedsos.js",
        "WebSo"                     => "_Page/WebSo/WebSo.js",
        "WebArtikel"                => "_Page/WebArtikel/WebArtikel.js",
        "WebEvent"                  => "_Page/WebEvent/WebEvent.js",
        "WebArsip"                  => "_Page/WebArsip/WebArsip.js",
        "WebDokter"                 => "_Page/WebDokter/WebDokter.js",
        "WebPoliklinik"             => "_Page/WebPoliklinik/WebPoliklinik.js",
        "WebSambutan"               => "_Page/WebSambutan/WebSambutan.js",
        "WebRuangRawat"             => "_Page/WebRuangRawat/WebRuangRawat.js",
        "WebUnit"                   => "_Page/WebUnit/WebUnit.js",
        "WebTestimoni"              => "_Page/WebTestimoni/WebTestimoni.js",
        "WebEmailGateway"           => "_Page/WebEmailGateway/WebEmailGateway.js",
        "WebLoker"                  => "_Page/WebLoker/WebLoker.js",
        "WebBantuan"                => "_Page/WebBantuan/WebBantuan.js",
        "WebHubungiAdmin"           => "_Page/WebHubungiAdmin/WebHubungiAdmin.js",
        "WebSiteMap"                => "_Page/WebSiteMap/WebSiteMap.js",
        "WebMonitoring"             => "_Page/WebMonitoring/WebMonitoring.js",
        "WebFooter"                 => "_Page/WebFooter/WebFooter.js",
        "WebLaman"                  => "_Page/WebLaman/WebLaman.js",
        "WebAksesPasien"            => "_Page/WebAksesPasien/WebAksesPasien.js",
        "WebKunjungan"              => "_Page/WebKunjungan/WebKunjungan.js",
        "Radiologi"                 => "_Page/Radiologi/Radiologi.js?v='.$version.'",
        "Laboratorium"              => "_Page/Laboratorium/Laboratorium.js?v='.$version.'",
        "Laboratorium2"              => "_Page/Laboratorium2/Laboratorium2.js?v='.$version.'",
        "Setting"                   => "_Page/Setting/Setting.js",
        "sep"                       => "_Page/sep/sep.js",
        "DashboardAntrol"           => "_Page/DashboardAntrol/DashboardAntrol.js",
        "LaporanPengguna"           => "_Page/LaporanPengguna/LaporanPengguna.js",
        "StokOpename"               => "_Page/StokOpename/StokOpename.js",
        "Resep"                     => "_Page/Resep/Resep.js",
        "ExpiredLimit"              => "_Page/ExpiredLimit/ExpiredLimit.js",
        "TarifTindakan"             => "_Page/TarifTindakan/TarifTindakan.js",
        "Supplier"                  => "_Page/Supplier/Supplier.js",
        "AkunPerkiraan"             => "_Page/AkunPerkiraan/AkunPerkiraan.js",
        "Transaksi"                 => "_Page/Transaksi/Transaksi.js",
        "SirsOnline"                => "_Page/SirsOnline/SirsOnline.js",
        "SirsOnlineAntrian"         => "_Page/SirsOnlineAntrian/SirsOnlineAntrian.js",
        "PasienShk"                 => "_Page/PasienShk/PasienShk.js",
        "SirsOnlineOksigen"         => "_Page/SirsOnlineOksigen/SirsOnlineOksigen.js",
        "SirsOnlineTempatTidur"     => "_Page/SirsOnlineTempatTidur/SirsOnlineTempatTidur.js",
        "SirsOnlineAlkes"           => "_Page/SirsOnlineAlkes/SirsOnlineAlkes.js",
        "SirsOnlineNakesTerinfeksi" => "_Page/SirsOnlineNakesTerinfeksi/SirsOnlineNakesTerinfeksi.js",
        "Alergi"                    => "_Page/Alergi/Alergi.js",
        "Kfa"                       => "_Page/Kfa/Kfa.js",
        "Medication"                => "_Page/Medication/Medication.js",
        "Api"                       => "_Page/Api/Api.js",
        "Radix"                     => "_Page/Radix/Radix.js",
        "Analyza"                   => "_Page/Analyza/Analyza.js",
        "TopDiagnosa"               => "_Page/TopDiagnosa/TopDiagnosa.js",
        "Jurnal"                    => "_Page/Jurnal/Jurnal.js",
        "BukuBesar"                 => "_Page/BukuBesar/BukuBesar.js",
        "NeracaSaldo"               => "_Page/NeracaSaldo/NeracaSaldo.js",
        "Persediaan"                => "_Page/Persediaan/Persediaan.js",
        "PersediaanFarmasi"         => "_Page/PersediaanFarmasi/PersediaanFarmasi.js",
        "Kas"                       => "_Page/Kas/Kas.js",
        "Anggaran"                  => "_Page/Anggaran/Anggaran.js"
    ];

    // Load file JS sesuai halaman aktif
    if (isset($Page) && isset($pages[$Page])) {
        echo '<script type="text/javascript" src="' . htmlspecialchars($pages[$Page], ENT_QUOTES, 'UTF-8') . '"></script>' . PHP_EOL;
    }

    // Tambahan default script (selalu dimuat)
    echo '<script type="text/javascript" src="_Page/Dashboard/Dashboard.js?v='.$version.'"></script>' . PHP_EOL;
?>
