<?php
    //Koneksi
    date_default_timezone_set('Asia/Jakarta');
    include "../../_Config/Connection.php";
    include "../../_Config/Session.php";
    include "../../_Config/SimrsFunction.php";
    if(!empty($_POST['CodeSystemLoinc'])){
        $CodeSystemLoinc=$_POST['CodeSystemLoinc'];
        if($CodeSystemLoinc=="8867-4|Heart rate"){
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="tipe_value">TipeData</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" readonly class="form-control" name="tipe_value" id="tipe_value" value="valueQuantity">';
            echo '  </div>';
            echo '</div>';
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="value">Value</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" class="form-control" name="value" id="value">';
            echo '  </div>';
            echo '</div>';
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="unit">Unit</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" readonly class="form-control" name="unit" id="unit" value="beats/minute">';
            echo '  </div>';
            echo '</div>';
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="CodeUnit">Code Unit</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" readonly class="form-control" name="CodeUnit" id="CodeUnit" value="/min">';
            echo '  </div>';
            echo '</div>';
        }
        if($CodeSystemLoinc=="8480-6|Systolic blood pressure"||$CodeSystemLoinc=="8462-4|Diastolic blood pressure"){
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="tipe_value">TipeData</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" readonly class="form-control" name="tipe_value" id="tipe_value" value="valueQuantity">';
            echo '  </div>';
            echo '</div>';
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="value">Value</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" class="form-control" name="value" id="value">';
            echo '  </div>';
            echo '</div>';
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="unit">Unit</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" readonly class="form-control" name="unit" id="unit" value="mm[Hg]">';
            echo '  </div>';
            echo '</div>';
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="CodeUnit">Code Unit</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" readonly class="form-control" name="CodeUnit" id="CodeUnit" value="mm[Hg]">';
            echo '  </div>';
            echo '</div>';
        }
        if($CodeSystemLoinc=="8310-5|Body temperature"){
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="tipe_value">TipeData</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" readonly class="form-control" name="tipe_value" id="tipe_value" value="valueQuantity">';
            echo '  </div>';
            echo '</div>';
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="value">Value</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" class="form-control" name="value" id="value">';
            echo '  </div>';
            echo '</div>';
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="unit">Unit</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" readonly class="form-control" name="unit" id="unit" value="C">';
            echo '  </div>';
            echo '</div>';
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="CodeUnit">Code Unit</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" readonly class="form-control" name="CodeUnit" id="CodeUnit" value="Cel">';
            echo '  </div>';
            echo '</div>';
        }
        if($CodeSystemLoinc=="9279-1|Respiratory rate"){
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="tipe_value">TipeData</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" readonly class="form-control" name="tipe_value" id="tipe_value" value="valueQuantity">';
            echo '  </div>';
            echo '</div>';
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="value">Value</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" class="form-control" name="value" id="value">';
            echo '  </div>';
            echo '</div>';
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="unit">Unit</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" readonly class="form-control" name="unit" id="unit" value="breaths/minute">';
            echo '  </div>';
            echo '</div>';
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="CodeUnit">Code Unit</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" readonly class="form-control" name="CodeUnit" id="CodeUnit" value="/min">';
            echo '  </div>';
            echo '</div>';
        }
        if($CodeSystemLoinc=="67775-7|Level of responsiveness"){
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="tipe_value">TipeData</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <input type="text" class="form-control" name="tipe_value" id="tipe_value" value="valueCodeableConcept">';
            echo '  </div>';
            echo '</div>';
            echo '<div class="row mb-3">';
            echo '  <div class="col-md-4">';
            echo '      <label for="value">Value</label>';
            echo '  </div>';
            echo '  <div class="col-md-8">';
            echo '      <select class="form-control" name="value" id="value">';
            echo '          <option value="TK000001|Alert">Sadar Baik</option>';
            echo '          <option value="TK000002|Voice">Berespon dengan kata-kata</option>';
            echo '          <option value="TK000003|Pain">Hanya berespons jika dirangsang nyeri</option>';
            echo '          <option value="TK000004|Unresponsive">Pasien Tidak Sadar</option>';
            echo '          <option value="TK000005|Gelisah">Pasien Tidak Sadar</option>';
            echo '          <option value="TK000006|Acute Confusional States">Acute Confusional States</option>';
            echo '      </select>';
            echo '  </div>';
            echo '</div>';
        }
    }
?>